### ISSUE TITLE
Set a server as a command centre for players in game

### ISSUE THREAD

**Issue by ghost** [frozenmistadventure/fmetp_tutorial_questvr_stream#1]
Hi Frozenmist Adventure,

I am andrew and my company FX Media had bought your V2 asset for not so long ago, I am the programmer there. I tried to implement this function to VR game we're recently planning, the case is that we have 4 players (clients) joined with PUN 2, and there is one command centre to monitor the game, the command centre can start the game if 4 players joined the lobby, and when the 4 players/clients joined, the command centre (server) can watch 4 different views of players, meaning that it has 2 raw image screens on top and bottom (left & right). I've been trying to make 4 GameViewDecoders for 4 different players, but it overlapped each other.

We hope we can get suggestions from you guys. By the way, it's a very nice asset.

Thanks and God Bless.

Andrew Paul
FX Media Programmer

**Comment by frozenmistadventure** [comment]
Hi Paul,

Thanks for reaching out to us.

Option1: There is a label ID for the pairing of different encoder & decoder.

Or Option2:
you may consider instantiate them as networked object, and send the data
via serialised stream on itself. each networked object including both
encoder/decoder.
but, only the sender will enable the encoder while the receiver will enable
the decoder.

There are few many methods to set them up with PUN2, depending on your use
case.

Cheers,
Leoson

**Comment by ghost** [comment]
Woah thanks Leoson, that makes sense !

Thanks a lot, God bless
