### ISSUE TITLE
Duplicate symbol error building for iOS | Unity 2021.3.21f1 | FMETP 3.0 v3.380

### ISSUE THREAD

**Issue by DevLars-rookie** [frozenmistadventure/fmetp_tutorial_questvr_stream#2]
Hi,
im tyring to build an iOS app from Unity but when i compile the XCode Project i get following error

```
   + [arm64] Linking UnityFramework...
ld64.lld: error: duplicate symbol: jpeg_add_quant_table
>>> defined in jcparam.c:36 (External/libjpeg-turbo/src\jcparam.c:36)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)

ld64.lld: error: duplicate symbol: jpeg_set_linear_quality
>>> defined in jcparam.c:120 (External/libjpeg-turbo/src\jcparam.c:120)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)

ld64.lld: error: duplicate symbol: jpeg_quality_scaling
>>> defined in jcparam.c:137 (External/libjpeg-turbo/src\jcparam.c:137)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)

ld64.lld: error: duplicate symbol: jpeg_set_quality
>>> defined in jcparam.c:162 (External/libjpeg-turbo/src\jcparam.c:162)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)

ld64.lld: error: duplicate symbol: jpeg_set_defaults
>>> defined in jcparam.c:183 (External/libjpeg-turbo/src\jcparam.c:183)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)

ld64.lld: error: duplicate symbol: jpeg_default_colorspace
>>> defined in jcparam.c:284 (External/libjpeg-turbo/src\jcparam.c:284)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)

ld64.lld: error: duplicate symbol: jpeg_set_colorspace
>>> defined in jcparam.c:325 (External/libjpeg-turbo/src\jcparam.c:325)
>>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
>>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
```
How to resolve?

Best regards
DevLars

**Comment by frozenmistadventure** [comment]
> Hi, im tyring to build an iOS app from Unity but when i compile the XCode Project i get following error
> 
> ```
>    + [arm64] Linking UnityFramework...
> ld64.lld: error: duplicate symbol: jpeg_add_quant_table
> >>> defined in jcparam.c:36 (External/libjpeg-turbo/src\jcparam.c:36)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> 
> ld64.lld: error: duplicate symbol: jpeg_set_linear_quality
> >>> defined in jcparam.c:120 (External/libjpeg-turbo/src\jcparam.c:120)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> 
> ld64.lld: error: duplicate symbol: jpeg_quality_scaling
> >>> defined in jcparam.c:137 (External/libjpeg-turbo/src\jcparam.c:137)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> 
> ld64.lld: error: duplicate symbol: jpeg_set_quality
> >>> defined in jcparam.c:162 (External/libjpeg-turbo/src\jcparam.c:162)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> 
> ld64.lld: error: duplicate symbol: jpeg_set_defaults
> >>> defined in jcparam.c:183 (External/libjpeg-turbo/src\jcparam.c:183)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> 
> ld64.lld: error: duplicate symbol: jpeg_default_colorspace
> >>> defined in jcparam.c:284 (External/libjpeg-turbo/src\jcparam.c:284)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> 
> ld64.lld: error: duplicate symbol: jpeg_set_colorspace
> >>> defined in jcparam.c:325 (External/libjpeg-turbo/src\jcparam.c:325)
> >>>            F:/_iOS_BUILD/Libraries\libiPhone-lib.a(jcparam_wd155.o)
> >>> defined in F:/_iOS_BUILD/Libraries/FMETP_STREAM/FMCore/Plugins/FMTurboJpeg/iOS\libturbojpeg.a(jcparam.c.o)
> ```
> 
> How to resolve?
> 
> Best regards DevLars

What's your OSX version, Unity version and Xcode version?
We will do a quick compile test soon to verify your issue.

Edited:
I've tried compiling the demo scenes via XCode 14.3.1, on m1 Max OSX 13.4.1 with Unity 2022.3.0f1 successfully.
Archived in Xcode, exported as Development ".ipa", all working fine without error.

**Comment by frozenmistadventure** [comment]
This issue has been solved, everything works correctly on Mac OS.
PS: Unity Editor(Windows PC) will generate wrong XCode project with above errors, please use Mac OS to build and compile the ".ipa"
