### ISSUE TITLE
Connection but no Image on Quest 2/3

### ISSUE THREAD

**Issue by lixsldotnet** [frozenmistadventure/fmetp_tutorial_questvr_stream#3]
Hey,
im trying to build an VR-Viewer for my VR App. 
I build an setup like this tutorial. It works when i start Client and Server on the same machine. 
But if i put the App on the Quest the Viewing Client finds the Server (Quest), Connects to it, sends and resieves data seen in the debug log but the preview image stays white. 

Is there an known bug or something im missing like permissions for andoriod?

Im using unity 2202.3.14f1 and FMETP Stream 3.411

thanks in advance

**Comment by frozenmistadventure** [comment]
> Hey, im trying to build an VR-Viewer for my VR App. I build an setup like this tutorial. It works when i start Client and Server on the same machine. But if i put the App on the Quest the Viewing Client finds the Server (Quest), Connects to it, sends and resieves data seen in the debug log but the preview image stays white.
> 
> Is there an known bug or something im missing like permissions for andoriod?
> 
> thanks in advance

If you are using URP for Quest VR, please try switching from multi-view to multi-pass in Oculus Stereo Rendering Mode settings.

PS: as far as I remember, this is a known Unity Engine bug related to Quest URP, and render texture specific issue.

**Comment by lixsldotnet** [comment]
Thanks for the quick anwser. 

This worked! I trying to figure this out since December. Thanks the next coffee goes on me.
